# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nwa < Formula
  desc "NWA - A More Powerful License Header Management Tool"
  homepage "https://github.com/B1NARY-GR0UP/nwa"
  version "0.7.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.7.8/nwa_Darwin_x86_64.tar.gz"
      sha256 "2dff2a39d51b4360b455d7998a737df70327808515facb77c7a32465f7c9f396"

      define_method(:install) do
        bin.install "nwa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.7.8/nwa_Darwin_arm64.tar.gz"
      sha256 "be3eb43a060337863525192fe96ebf138e8b99ed902a8accbf97619cc7b29f54"

      define_method(:install) do
        bin.install "nwa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.7.8/nwa_Linux_x86_64.tar.gz"
      sha256 "b50d29d4bfb0d4b1a35256fbdd0d54119af520de0305325a5783519449a8dd0f"
      define_method(:install) do
        bin.install "nwa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.7.8/nwa_Linux_arm64.tar.gz"
      sha256 "2b8dd65f7ef34b0f5ad7fada778d5a14ab8e4a9fbf6389ea5e9167d012c8502c"
      define_method(:install) do
        bin.install "nwa"
      end
    end
  end

  test do
    system "#{bin}/nwa --version"
  end
end
