# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nwa < Formula
  desc "NWA - A More Powerful License Header Management Tool"
  homepage "https://github.com/B1NARY-GR0UP/nwa"
  version "0.7.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.7.7/nwa_Darwin_x86_64.tar.gz"
      sha256 "afbaf424598a65a3c4b1149f7d03fda69fdd636a0907582e55a3d8078320f296"

      def install
        bin.install "nwa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.7.7/nwa_Darwin_arm64.tar.gz"
      sha256 "1483b3d14d94b913e98a26779c5088f065f570b14f24a01de9ad39d8d578ea90"

      def install
        bin.install "nwa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.7.7/nwa_Linux_x86_64.tar.gz"
      sha256 "d3fc8fe70ddb00fb41755d8486f347f5033770cb71b3effa2535f84412e2f807"
      def install
        bin.install "nwa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.7.7/nwa_Linux_arm64.tar.gz"
      sha256 "d0a7874a452307f79e444e68841658fe9b1d521ba14019d373f829d08c4b6835"
      def install
        bin.install "nwa"
      end
    end
  end

  test do
    system "#{bin}/nwa --version"
  end
end
